import CornerElements from "@/components/CornerElements";
import { ShieldIcon } from "lucide-react";

export const metadata = {
  title: "Terms of Service — Fitmax.ai",
  description: "Read the Terms of Service for Fitmax.ai. Understand your rights and responsibilities when using our AI fitness platform.",
};

const sections = [
  {
    title: "1. Acceptance of Terms",
    content: `By accessing or using Fitmax.ai ("the App"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the App. These Terms apply to all visitors, users, and others who access or use the App.`,
  },
  {
    title: "2. Description of Service",
    content: `Fitmax.ai is an AI-powered personal fitness platform that provides personalized workout and diet plans through voice-based AI interactions, exercise tracking tools, performance analytics, and access to a curated exercise library. The App is provided for informational and educational purposes only.`,
  },
  {
    title: "3. Health & Fitness Disclaimer",
    content: `The fitness and nutrition information provided by Fitmax.ai, including plans generated by our AI assistant, is for general informational purposes and is not a substitute for professional medical advice, diagnosis, or treatment. Always consult your physician or qualified health provider before beginning any new exercise or diet program. Fitmax.ai is not responsible for any injuries or health issues that may result from following the plans or advice provided.`,
  },
  {
    title: "4. User Accounts",
    content: `To use certain features of the App, you must register for an account through our authentication provider (Clerk). You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.`,
  },
  {
    title: "5. User Conduct",
    content: `You agree not to misuse the App. This includes, but is not limited to: attempting to circumvent AI safety filters, scraping or harvesting data from the App, using the App for commercial purposes without our prior written consent, or engaging in any activity that disrupts or interferes with the App or its connected services.`,
  },
  {
    title: "6. Intellectual Property",
    content: `All content, features, and functionality of the App — including but not limited to text, graphics, logos, and software — are the exclusive property of Fitmax.ai and its licensors. You may not reproduce, distribute, or create derivative works without our express written permission.`,
  },
  {
    title: "7. Termination",
    content: `We reserve the right to suspend or terminate your access to the App at any time, with or without cause or notice, including for violations of these Terms. Upon termination, your right to use the App will immediately cease.`,
  },
  {
    title: "8. Limitation of Liability",
    content: `To the maximum extent permitted by law, Fitmax.ai and its officers, directors, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the App.`,
  },
  {
    title: "9. Changes to Terms",
    content: `We reserve the right to modify these Terms at any time. We will notify you of changes by updating the date at the bottom of this page. Continued use of the App after changes constitutes acceptance of the updated Terms.`,
  },
  {
    title: "10. Governing Law",
    content: `These Terms shall be governed by and construed in accordance with the laws of the applicable jurisdiction, without regard to its conflict of law provisions.`,
  },
];

export default function TermsPage() {
  return (
    <main className="min-h-screen pt-24 pb-20 container mx-auto px-4 max-w-4xl">
      <div className="text-center mb-12">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-primary/30 bg-primary/10 text-primary text-xs font-mono mb-6">
          <ShieldIcon className="w-3 h-3" /> LEGAL
        </div>
        <h1 className="text-4xl font-bold font-mono mb-4">
          Terms of <span className="text-primary">Service</span>
        </h1>
        <p className="text-muted-foreground">Last updated: March 14, 2025</p>
      </div>

      <div className="relative border border-border rounded-none p-6 mb-8 overflow-hidden bg-primary/5">
        <CornerElements />
        <p className="text-sm text-muted-foreground leading-relaxed">
          Please read these Terms carefully before using Fitmax.ai. By using the App, you acknowledge that you have read, understood, and agree to be bound by these Terms.
        </p>
      </div>

      <div className="space-y-8">
        {sections.map((section) => (
          <div key={section.title} className="border-b border-border/50 pb-8 last:border-0">
            <h2 className="text-lg font-bold font-mono text-primary mb-3">{section.title}</h2>
            <p className="text-muted-foreground leading-relaxed text-sm">{section.content}</p>
          </div>
        ))}
      </div>
    </main>
  );
}
